import { elifood, casablanca, lovinghutland, morococo, ezindia, kervan, taj, chabad, petras, sultan, dubai, everest, zerovegan, greener, chezvalerie, dinerjackie, apbbang, vegetus } from './imports';

const Data = [
  {
    id: "1",
    title: "Casablanca",
    category: "Halal",
    img: casablanca,
    desc: "35, Sinheung-ro, Yongsan-gu, Seoul(서울시 용산구 신흥로 35)",
  },
  {
    id: "2",
    title: "Loving Hut Land",
    category: "Halal",
    img: lovinghutland,
    desc: "17, Nonhyeon-ro 16-gil, Gangnam-gu, Seoul(서울특별시 강남구 논현로16길 17)",
  },
  {
    id: "3",
    title: "Morococo Cafe",
    category: "Halal",
    img: morococo,
    desc: "34, Sinheung-ro, Yongsan-gu, Seoul(서울시 용산구 신흥로 34)",
  },
  {
    id: "4",
    title: "Ezindia",
    category: "Halal",
    img: ezindia,
    desc: "3F, 20, Yonsei-ro, Seodaemun-gu, Seoul(서울시 서대문구 연세로 20 3층)",
  },
  {
    id: "5",
    title: "KERVAN Famille Branch",
    category: "Halal",
    img: kervan,
    desc: "2F, 205, Sapyeong-daero, Seocho-gu, Seoul(서울시 서초구 사평대로 205 2층)",
  },
  {
    id: "6",
    title: "Taj",
    category: "Halal",
    img: taj,
    desc: "2F, 73, Myeongdong-gil, Jung-gu, Seoul(서울 중구 명동길 73)",
  },
  {
    id: "7",
    title: "Kosher Eli Food",
    category: "Kosher",
    img: elifood,
    desc: "43 Hoenamu-ro 26-gil, Itaewon 2(i)-dong, Yongsan-gu, Seoul",
  },
  {
    id: "8",
    title: "Chabad Korea",
    category: "Kosher",
    img: chabad,
    desc: "35-10, Itaewon-ro 49-gil, Yongsan-gu, Seoul",
  },
  {
    id: "9",
    title: "Petra",
    category: "Kosher",
    img: petras,
    desc: "33 Noksapyeong-daero 40-gil, Yongsan-gu, Seoul",
  },
  {
    id: "10",
    title: "Sultan Kebab",
    category: "Kosher",
    img: sultan,
    desc: "126 Bogwang-ro, Yongsan-gu, Seoul",
  },
  {
    id: "11",
    title: "Everest",
    category: "Kosher",
    img: everest,
    desc: "2-1 Jong-ro 51ga-gil, Jongno-gu, Seoul",
  },
  {
    id: "12",
    title: "Dubai",
    category: "Kosher",
    img: dubai,
    desc: "192 Itaewon-ro, Itaewon-dong, Yongsan-gu, Seoul",
  },
  {
    id: "13",
    title: "Zero Vegan",
    category: "Vegetarian",
    img: zerovegan,
    desc: "2 floor, 117 Bogwang-ro, Yongsan-gu, Seoul",
  },
  {
    id: "14",
    title: "Greener",
    category: "Vegetarian",
    img: greener,
    desc: "157 1층, Seongmisan-ro, Mapo-gu, Seoul",
  },
  {
    id: "15",
    title: "Chez Valérie",
    category: "Vegetarian",
    img: chezvalerie,
    desc: "433-60 Hapjeong-dong, Mapo-gu, Seoul",
  },
  {
    id: "16",
    title: "Apbbang",
    category: "Vegetarian",
    img: apbbang,
    desc: "Samil-daero 32ga-gil, Jongno-gu, 29-1, Seoul",
  },
  {
    id: "17",
    title: "Diner Jackie",
    category: "Vegetarian",
    img: dinerjackie,
    desc: "82 Poeun-ro, Mangwon-dong, Mapo-gu, Seoul",
  },
  {
    id: "18",
    title: "Vegetus",
    category: "Vegetarian",
    img: vegetus,
    desc: "Yongsan-dong 2-ga 22-12, Seoul",
  },
  {
    id: "19",
    title: "Casablanca",
    category: "Halal",
    img: casablanca,
    desc: "35, Sinheung-ro, Yongsan-gu, Seoul(서울시 용산구 신흥로 35)",
  },
  {
    id: "20",
    title: "Loving Hut Land",
    category: "Halal",
    img: lovinghutland,
    desc: "17, Nonhyeon-ro 16-gil, Gangnam-gu, Seoul(서울특별시 강남구 논현로16길 17)",
  },
  {
    id: "21",
    title: "Morococo Cafe",
    category: "Halal",
    img: morococo,
    desc: "34, Sinheung-ro, Yongsan-gu, Seoul(서울시 용산구 신흥로 34)",
  },
  {
    id: "22",
    title: "Ezindia",
    category: "Halal",
    img: ezindia,
    desc: "3F, 20, Yonsei-ro, Seodaemun-gu, Seoul(서울시 서대문구 연세로 20 3층)",
  },
  {
    id: "23",
    title: "Taj",
    category: "Kosher",
    img: taj,
    desc: "2F, 73, Myeongdong-gil, Jung-gu, Seoul(서울 중구 명동길 73)",
  },
  {
    id: "24",
    title: "Kosher Eli Food",
    category: "Kosher",
    img: elifood,
    desc: "43 Hoenamu-ro 26-gil, Itaewon 2(i)-dong, Yongsan-gu, Seoul",
  },
  {
    id: "25",
    title: "Zero Vegan",
    category: "Vegetarian",
    img: zerovegan,
    desc: "2 floor, 117 Bogwang-ro, Yongsan-gu, Seoul",
  },
  {
    id: "26",
    title: "Greener",
    category: "Vegetarian",
    img: greener,
    desc: "157 1층, Seongmisan-ro, Mapo-gu, Seoul",
  },
  {
    id: "27",
    title: "Chez Valérie",
    category: "Vegetarian",
    img: chezvalerie,
    desc: "433-60 Hapjeong-dong, Mapo-gu, Seoul",
  },
  {
    id: "28",
    title: "Casablanca",
    category: "Halal",
    img: casablanca,
    desc: "35, Sinheung-ro, Yongsan-gu, Seoul(서울시 용산구 신흥로 35)",
  },
  {
    id: "29",
    title: "Loving Hut Land",
    category: "Halal",
    img: lovinghutland,
    desc: "17, Nonhyeon-ro 16-gil, Gangnam-gu, Seoul(서울특별시 강남구 논현로16길 17)",
  },
  {
    id: "30",
    title: "Morococo Cafe",
    category: "Halal",
    img: morococo,
    desc: "34, Sinheung-ro, Yongsan-gu, Seoul(서울시 용산구 신흥로 34)",
  },
  {
    id: "31",
    title: "Ezindia",
    category: "Halal",
    img: ezindia,
    desc: "3F, 20, Yonsei-ro, Seodaemun-gu, Seoul(서울시 서대문구 연세로 20 3층)",
  },
  {
    id: "32",
    title: "Taj",
    category: "Kosher",
    img: taj,
    desc: "2F, 73, Myeongdong-gil, Jung-gu, Seoul(서울 중구 명동길 73)",
  },
  {
    id: "33",
    title: "Kosher Eli Food",
    category: "Kosher",
    img: elifood,
    desc: "43 Hoenamu-ro 26-gil, Itaewon 2(i)-dong, Yongsan-gu, Seoul",
  },
  {
    id: "34",
    title: "Zero Vegan",
    category: "Vegetarian",
    img: zerovegan,
    desc: "2 floor, 117 Bogwang-ro, Yongsan-gu, Seoul",
  },
  {
    id: "35",
    title: "Greener",
    category: "Vegetarian",
    img: greener,
    desc: "157 1층, Seongmisan-ro, Mapo-gu, Seoul",
  },
  {
    id: "36",
    title: "Chez Valérie",
    category: "Vegetarian",
    img: chezvalerie,
    desc: "433-60 Hapjeong-dong, Mapo-gu, Seoul",
  },
  {
    id: "37",
    title: "Casablanca",
    category: "Halal",
    img: casablanca,
    desc: "35, Sinheung-ro, Yongsan-gu, Seoul(서울시 용산구 신흥로 35)",
  },
  {
    id: "38",
    title: "Loving Hut Land",
    category: "Halal",
    img: lovinghutland,
    desc: "17, Nonhyeon-ro 16-gil, Gangnam-gu, Seoul(서울특별시 강남구 논현로16길 17)",
  },
  {
    id: "39",
    title: "Morococo Cafe",
    category: "Halal",
    img: morococo,
    desc: "34, Sinheung-ro, Yongsan-gu, Seoul(서울시 용산구 신흥로 34)",
  },
  {
    id: "40",
    title: "Ezindia",
    category: "Halal",
    img: ezindia,
    desc: "3F, 20, Yonsei-ro, Seodaemun-gu, Seoul(서울시 서대문구 연세로 20 3층)",
  },
  {
    id: "41",
    title: "Taj",
    category: "Kosher",
    img: taj,
    desc: "2F, 73, Myeongdong-gil, Jung-gu, Seoul(서울 중구 명동길 73)",
  },
  {
    id: "42",
    title: "Kosher Eli Food",
    category: "Kosher",
    img: elifood,
    desc: "43 Hoenamu-ro 26-gil, Itaewon 2(i)-dong, Yongsan-gu, Seoul",
  },
  {
    id: "43",
    title: "Zero Vegan",
    category: "Vegetarian",
    img: zerovegan,
    desc: "2 floor, 117 Bogwang-ro, Yongsan-gu, Seoul",
  },
  {
    id: "44",
    title: "Greener",
    category: "Vegetarian",
    img: greener,
    desc: "157 1층, Seongmisan-ro, Mapo-gu, Seoul",
  },
  {
    id: "45",
    title: "Chez Valérie",
    category: "Vegetarian",
    img: chezvalerie,
    desc: "433-60 Hapjeong-dong, Mapo-gu, Seoul",
  },

];

export default Data;
